[build]
target = "xtensa-esp32s3-espidf"

[target.'cfg(target_os = "espidf")']
linker = "ldproxy"
rustflags = [
  "--cfg",
  "espidf_time64",
  "-C",
  "link-args=--ldproxy-linker",
  "-C",
  "link-args=xtensa-esp32s3-elf-gcc",
]

[unstable]
build-std = ["std", "panic_abort"]

[env]
ESP_IDF_TOOLS_INSTALL_DIR = { value = "fromenv", force = true }
IDF_COMPONENT_MANAGER = { value = "0", force = true }
ESP_IDF_SDKCONFIG_DEFAULTS = { value = "sdkconfig.defaults;sdkconfig.rust.defaults", force = true, relative = true }
